Update README.md
charliefoxtwo/TouchDCS pull request #13
Opened 2021-06-10 08:01 UTC by jansvensson

Fixed missing (

2021-06-10 15:57 UTC, charliefoxtwo commented on README.md
> +1. DCS-BIOS [Flightpanels fork]((https://github.com/DCSFlightpanels/dcs-bios))
Actually, there should just be a single parenthesis on either side so the markdown link works. It should look something like this: `[Google](www.google.com)`. Check out [this guide](https://www.markdownguide.org/basic-syntax/#links) for more info.

2021-06-11 02:13 UTC, charliefoxtwo requested changes

2021-06-11 02:13 UTC, charliefoxtwo commented on README.md
> +1. DCS-BIOS [Flightpanels fork]((https://github.com/DCSFlightpanels/dcs-bios))
```suggestion
1. DCS-BIOS [Flightpanels fork](https://github.com/DCSFlightpanels/dcs-bios)
```

2021-06-11 06:33 UTC, jansvensson commented
Got it! Nice catch :)

2021-06-11 06:40 UTC, charliefoxtwo approved these changes

2021-06-11 06:41 UTC, merged